export { default as HomeScreen } from "./HomeScreen";
export { default as Dashboard } from "./Admin/Dashboard";
export { default as Confirmation } from "./Admin/Confirmation";
export { default as EditConfirmation } from "./Admin/Confirmation/Edit";
export { default as Roles } from "./Admin/Config/";
export { default as Location } from "./Admin/Config/Location";
export { default as Division } from "./Admin/Config/Division";
export { default as AdminPending } from "./Admin/Pending";
export { default as AdminViewPending } from "./Admin/Pending/View";
export { default as AdminCompleted } from "./Admin/Completed";
export { default as RequestPage } from "./ConfirmationForm/RequestPage";
export { default as behavioral_Section1 } from "./ConfirmationForm/performanceFactor/Others/behaviouralTrait";
export { default as Rater_behavioral_Section1 } from "./ConfirmationForm/performanceFactor/Raters/behaviouralTrait";
export { default as Section2 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2";
export { default as Section3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3";
export { default as Section1__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 1";
export { default as Section2__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 2";
export { default as PendingRequests } from "./ConfirmationForm/PendingRequests";
export { default as LineManagerPendingPage } from "./ConfirmationForm/PendingRequests/LineManagerPendingPage";
export { default as HrbpPendingPage } from "./ConfirmationForm/PendingRequests/HrbpPendingPage";
export { default as HrAdminstrationPendingPage } from "./ConfirmationForm/PendingRequests/HrAdminstrationPendingPage";
export { default as SeniorManagerESPendingPage } from "./ConfirmationForm/PendingRequests/SeniorManagerESPendingPage";
export { default as GmHrOperationsPendingPage } from "./ConfirmationForm/PendingRequests/GmHrOperationsPendingPage";
export { default as ViewRequestDetails } from "./ConfirmationForm/ViewRequestDetails";
export { default as Rater_Performance_Section1 } from "./ConfirmationForm/performanceFactor/Raters/pageOne";
export { default as Rater_Performance_Section2 } from "./ConfirmationForm/performanceFactor/Raters/pageTwo";
export { default as Performance_Section1 } from "./ConfirmationForm/performanceFactor/Others/pageOne";
export { default as Performance_Section2 } from "./ConfirmationForm/performanceFactor/Others/pageTwo";
export { default as GetSuperVisorySection1 } from "./ConfirmationForm/Supervisory/Supervisory Section 1/GetSupervisorySection1";
export { default as GetBehavioralSection2Rating } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2/GetBehavioralSection2Rating";
export { default as GetBehavioralSection3Rating } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/GetBehavioralSection3Rating";
export { default as LineManagerView } from "./ConfirmationForm/Supervisory/view-ratings/LineManager";
export { default as ReviewerView } from "./ConfirmationForm/Supervisory/view-ratings/Reviewer";
export { default as ConfirmationSummary } from "./ConfirmationForm/Supervisory/view-ratings/ConfirmationSummary";
export { default as SMESView } from "./ConfirmationForm/Supervisory/view-ratings/SnrMgrEmployee";
export { default as MHRBPView } from "./ConfirmationForm/Supervisory/view-ratings/MHRBP";
export { default as HRAdminView } from "./ConfirmationForm/Supervisory/view-ratings/HRAdmin";
export { default as ManagerIndustrialRelationshipView } from "./ConfirmationForm/Supervisory/view-ratings/ManagerIndRel";
export { default as EmployeeView } from "./ConfirmationForm/Supervisory/view-ratings/Employee";
export { default as GMHRView } from "./ConfirmationForm/Supervisory/view-ratings/GMHr";
