export { default as HomeScreen } from "./HomeScreen";
export { default as Dashboard } from "./Admin/Dashboard";
export { default as Confirmation } from "./Admin/Confirmation";
export { default as EditConfirmation } from "./Admin/Confirmation/Edit";
export { default as Roles } from "./Admin/Config/";
export { default as Location } from "./Admin/Config/Location";
export { default as Division } from "./Admin/Config/Division";
export { default as AdminPending } from "./Admin/Pending";
export { default as AdminViewPending } from "./Admin/Pending/View";
export { default as AdminCompleted } from "./Admin/Completed";
export { default as RequestPage } from "./ConfirmationForm/RequestPage";
export { default as Section2 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2";
export { default as Section3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3";
export { default as Section1__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 1";
export { default as Section2__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 2";
export { default as PendingRequests } from "./ConfirmationForm/PendingRequests";
export { default as ViewRequestDetails } from "./ConfirmationForm/ViewRequestDetails";
